# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='get_time',
            field=models.DateField(verbose_name='\u83b7\u5f97\u65f6\u95f4'),
        ),
    ]
