# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20171014_1243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-create_time'], 'verbose_name': '\u6587\u7ae0\u4fe1\u606f', 'verbose_name_plural': '\u6587\u7ae0\u4fe1\u606f'},
        ),
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.IntegerField(default=0, verbose_name='\u6d4f\u89c8\u6570'),
        ),
    ]
