# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-22 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='emile',
            new_name='email',
        ),
    ]
