# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_name', models.CharField(max_length=128, verbose_name='\u5956\u9879\u540d\u79f0')),
                ('get_time', models.DateTimeField(verbose_name='\u83b7\u5f97\u65f6\u95f4')),
                ('description', models.TextField(verbose_name='\u5956\u9879\u5185\u5bb9')),
                ('give_man', models.CharField(choices=[('c', '\u6e29\u5927\u74ef\u6c5f\u7406\u5de5'), ('b', '\u6e29\u5927\u74ef\u6c5f'), ('a', '\u6e29\u5dde\u5927\u5b66')], max_length=1, verbose_name='\u9881\u53d1\u5355\u4f4d')),
            ],
            options={
                'verbose_name': '\u4e2a\u4eba\u5956\u9879',
                'verbose_name_plural': '\u4e2a\u4eba\u5956\u9879',
            },
        ),
    ]
