# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20171024_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='views',
        ),
    ]
